--1
SELECT * FROM EMP WHERE SAL > 3000;

--2
SELECT * FROM EMP WHERE ENAME LIKE 'S%';

--3
SELECT * FROM EMP WHERE ENAME IN ('SMITH', 'ALLEN', 'FORD');

--4
SELECT A.EMPNO, A.ENAME, B.DNAME
FROM EMP A
LEFT OUTER JOIN DEPT B
ON A.DEPTNO= A.DEPTNO
WHERE B.DNAME = 'SALES';

--5
SELECT AVG(A.SAL) AS AVE_SAL, MIN(A.SAL) AS MIN_SAL, MAX(A.SAL) AS MAX_SAL, B.DNAME
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO
GROUP BY B.DNAME;

--6
SELECT COUNT(A.ENAME) AS TOTAL_NUMBER_EMP, A.ENAME, B.DNAME
FROM EMP A, DEPT B
WHERE A.DEPTNO=B.DEPTNO AND
A.SAL>3000
GROUP BY B.DNAME, A.ENAME;

--7
SELECT AVG(A.SAL) AS AVE_SAL, B.DNAME
FROM EMP A, DEPT B
WHERE A.DEPTNO=B.DEPTNO
GROUP BY B.DNAME
ORDER BY AVG(A.SAL);

--8
SELECT COUNT(A.ENAME)AS TOTAL_NUMBER_EMP, C.DEPTNO, A.SAL
FROM EMP A, EMP B, DEPT C
WHERE A.DEPTNO=C.DEPTNO
AND A.SAL = B.SAL
AND A.ENAME != B.ENAME
GROUP BY C.DEPTNO, A.SAL;

--9
SELECT COUNT(A.ENAME),  
FROM EMP A, EMP B, DEPT C




SELECT * FROM DEPT