/*
 * File: app/store/UserStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Demo.store.UserStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Demo.model.UserModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'Demo.model.UserModel',
            storeId: 'UserStore',
            data: [
                {
                    userName: 'nesciunt',
                    passWord: 'ghh8KVfTeH'
                },
                {
                    userName: 'rerum',
                    passWord: '1KIET7u'
                },
                {
                    userName: 'ea',
                    passWord: 'EooIznYIay'
                },
                {
                    userName: 'odit',
                    passWord: 'O0tsGFMDPdf'
                },
                {
                    userName: 'magnam',
                    passWord: 'Vr4yIiUFUft'
                }
            ]
        }, cfg)]);
    }
});