CREATE TABLE W6D1_STUDENT(
  STUDENT_ID    VARCHAR2(100)   NOT NULL    PRIMARY KEY,
  STUDENT_NAME  VARCHAR2(100),
  STUDENT_SCORE NUMBER(3),
  TEACHER_ID    VARCHAR2(100),
  CONSTRAINT fk_teacher FOREIGN KEY (TEACHER_ID) REFERENCES W6D1_TEACHER(TEACHER_ID)
);

CREATE TABLE W6D1_TEACHER(
  TEACHER_ID    VARCHAR2(100)   NOT NULL    PRIMARY KEY,
  TEACHER_NAME  VARCHAR2(100),
  TEACHER_SCHOOL_NAME VARCHAR2(100)
);

CREATE TABLE W6D1_USER(
  USERNAME      VARCHAR2(50)    NOT NULL    PRIMARY KEY,
  USERFULLNAME  VARCHAR2(100)
);

CREATE TABLE W6D1_ORDER(
  ORDER_ID      NUMBER(9)       NOT NULL    PRIMARY KEY,
  ORDER_DESC    VARCHAR2(100),
  USERNAME      VARCHAR2(50),
  CONSTRAINT fk_user2 FOREIGN KEY (USERNAME) REFERENCES W6D1_USER(USERNAME)
);

CREATE TABLE W6D1_ORDERITEM(
  ORDERITEM_ID  NUMBER(9)       NOT NULL    PRIMARY KEY,
  ORDERITEM__DESC VARCHAR2(100),
  ORDER_ID      NUMBER(9),
  CONSTRAINT fk_order2 FOREIGN KEY (ORDER_ID) REFERENCES W6D1_ORDER(ORDER_ID)
);