--CREATE EMPLOYEE
CREATE TABLE EMPLOYEE(ID NUMBER(3) PRIMARY KEY, FIRST_NAME VARCHAR2(50), LAST_NAME VARCHAR2(50), MGRID NUMBER(3), SALARY NUMBER(7));
--INSERT INTO EMPLOYEE TABLE
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,MGRID,SALARY) VALUES(1,'rose','Tyler',4,1500);
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,MGRID,SALARY) VALUES(2,'Matha','Jones',4,2200);
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,MGRID,SALARY) VALUES(3,'Donna','Noble',4,1300);
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,SALARY) VALUES(4,'Doctor','Who',5500);
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,MGRID,SALARY) VALUES(5,'Jack','Harkness',4,3500);
COMMIT;
