-- MySQL Script generated by MySQL Workbench
-- 07/08/16 09:52:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema W4D4DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema W4D4DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `W4D4DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `W4D4DB` ;

-- -----------------------------------------------------
-- Table `W4D4DB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `W4D4DB`.`User` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userFname` VARCHAR(25) NOT NULL,
  `userLname` VARCHAR(25) NOT NULL,
  `userEmail` VARCHAR(15) NOT NULL,
  `userStreet` VARCHAR(25) NOT NULL,
  `userCity` VARCHAR(25) NOT NULL,
  `userCountry` VARCHAR(25) NOT NULL,
  `userPassword` VARCHAR(15) NOT NULL,
  `userType` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `W4D4DB`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `W4D4DB`.`Product` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(25) NOT NULL,
  `productDesc` VARCHAR(45) NULL,
  `productCategory` VARCHAR(25) NOT NULL,
  `productImg` VARCHAR(45) NOT NULL,
  `productPrice` DECIMAL(9,2) NOT NULL,
  `productStock` INT NOT NULL,
  PRIMARY KEY (`productId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `W4D4DB`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `W4D4DB`.`Order` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `orderTotal` DECIMAL(9,2) NOT NULL,
  `orderDate` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`orderId`),
  INDEX `userId_idx` (`userId` ASC),
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `W4D4DB`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `W4D4DB`.`OrderProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `W4D4DB`.`OrderProduct` (
  `orderProdId` INT NOT NULL AUTO_INCREMENT,
  `orderId` INT NOT NULL,
  `prodId` INT NOT NULL,
  `orderProdQty` INT NOT NULL,
  PRIMARY KEY (`orderProdId`),
  INDEX `orderId_idx` (`orderId` ASC),
  INDEX `productId_idx` (`prodId` ASC),
  CONSTRAINT `orderId`
    FOREIGN KEY (`orderId`)
    REFERENCES `W4D4DB`.`Order` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productId`
    FOREIGN KEY (`prodId`)
    REFERENCES `W4D4DB`.`Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
