CREATE TABLE USER_TABLE(
  USERNAME      VARCHAR2(50)      NOT NULL      PRIMARY KEY,
  PASSWORD      VARCHAR2(50)      NOT NULL,
  FULL_NAME     VARCHAR2(50)
);

CREATE TABLE ORDER_TABLE(
  ORDER_ID      NUMBER(3)       NOT NULL      PRIMARY KEY,
  ORDER_DESC    VARCHAR2(100),
  ORDER_DT      DATE,
  USERNAME    VARCHAR2(50),
  CONSTRAINT fk_user FOREIGN KEY (USERNAME) REFERENCES USER_TABLE(USERNAME)
);

CREATE TABLE ORDERITEM_TABLE(
  ORDERITEM_ID  NUMBER(3)       NOT NULL      PRIMARY KEY,
  ORDER_ID      NUMBER(3),
  ITEM_DESC     VARCHAR2(100),
  CONSTRAINT fk_order FOREIGN KEY (ORDER_ID) REFERENCES ORDER_TABLE(ORDER_ID)
);