/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W3D3_Homework.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'W3D3_Homework.view.MyViewportViewModel',
        'Ext.form.Panel',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.TextArea',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    viewModel: {
        type: 'myviewport'
    },
    anchorSize: 1,

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'form',
            width: 381,
            anchorSize: 1,
            bodyPadding: 10,
            title: 'W3D3_Homework',
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'First Name'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Last Name'
                        },
                        {
                            xtype: 'radiogroup',
                            flex: 0,
                            width: 277,
                            fieldLabel: 'Gender',
                            allowBlank: false,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    boxLabel: 'Male'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: 'Female'
                                }
                            ]
                        },
                        {
                            xtype: 'textareafield',
                            fieldLabel: 'Address'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: 'Birthday',
                            showToday: false
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Username'
                        },
                        {
                            xtype: 'textfield',
                            maskElement: '*',
                            fieldLabel: 'Password'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Register'
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    text: 'Login'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});