/*
 * File: app/store/ProductStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W5D5_Project.store.ProductStore', {
    extend: 'Ext.data.Store',

    requires: [
        'W5D5_Project.model.ProductModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'productStore',
            model: 'W5D5_Project.model.ProductModel',
            data: [
                {
                    prodId: 1,
                    prodName: 'Watch A',
                    prodCat: 'Sports',
                    prodDesc: 'voluptatem',
                    prodPrice: 739.76,
                    prodSale: 1,
                    prodStock: 814,
                    prodImg: 'A'
                },
                {
                    prodId: 2,
                    prodName: 'Watch B',
                    prodCat: 'Sports',
                    prodDesc: 'rem',
                    prodPrice: 255.16,
                    prodSale: 0.5,
                    prodStock: 496,
                    prodImg: 'B'
                },
                {
                    prodId: 3,
                    prodName: 'Watch C',
                    prodCat: 'Luxury',
                    prodDesc: 'nulla',
                    prodPrice: 871.02,
                    prodSale: 1,
                    prodStock: 371,
                    prodImg: 'C'
                }
            ]
        }, cfg)]);
    }
});