/*
 * File: app/store/RatingStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W5D5_Project.store.RatingStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'RatingStore',
            data: [
                {
                    rating: '1 - Poor',
                    value: '1'
                },
                {
                    rating: '2 - Fair',
                    value: '2'
                },
                {
                    rating: '3 - Good',
                    value: '3'
                },
                {
                    rating: '4 - Very Good',
                    value: '4'
                },
                {
                    rating: '5 - Excellent',
                    value: '5'
                }
            ],
            fields: [
                {
                    name: 'rating'
                },
                {
                    name: 'value'
                }
            ]
        }, cfg)]);
    }
});