/*
 * File: app/store/UserStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W3D5_Project.store.UserStore', {
    extend: 'Ext.data.Store',

    requires: [
        'W3D5_Project.model.UserModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'W3D5_Project.model.UserModel',
            storeId: 'UserStore',
            data: [
                {
                    fname: 'tenetur',
                    lname: 'possimus',
                    email: 'rsnyder@skajo.name',
                    username: 'bfreeman',
                    password: 'MdgzFMFvMWN',
                    address: '64 Mcbride Court',
                    id: 121
                },
                {
                    fname: 'eum',
                    lname: 'et',
                    email: 'probertson@thoughtstorm.com',
                    username: 'lcarroll',
                    password: '7lSFTlX',
                    address: '1 Jenifer Way',
                    id: 114
                },
                {
                    fname: 'sed',
                    lname: 'vel',
                    email: 'wsimpson@cogilith.info',
                    username: 'jlane',
                    password: 'eojHmHBIY1CO',
                    address: '685 Colorado Lane',
                    id: 204
                },
                {
                    fname: 'reiciendis',
                    lname: 'magni',
                    email: 'fsmith@meevee.org',
                    username: 'jhill',
                    password: 'oePymiLWjR',
                    address: '2 Delaware Terrace',
                    id: 901
                },
                {
                    fname: 'repellat',
                    lname: 'ratione',
                    email: 'jtucker@kanoodle.net',
                    username: 'bflores',
                    password: 'dRo8WiZ9g0',
                    address: '1036 Holmberg Lane',
                    id: 422
                }
            ]
        }, cfg)]);
    }
});