/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W3D5_Project.controller.Login', {
    extend: 'Ext.app.Controller',

    id: 'Login',

    onLoginbuttonClick: function() {
        if(Ext.isEmpty(this.gridWin)){
            this.gridWin = Ext.create('W3D5_Project.view.MainViewport', {});
        }
        this.gridWin.show();
        this.gridWin.unmask();
    },

    onRegisterbuttonClick: function() {
        if(Ext.isEmpty(this.gridWin)){
            this.gridWin = Ext.create('W3D5_Project.view.RegisterViewPort', {});
        }
        this.gridWin.show();
        this.gridWin.unmask();
    },

    init: function(application) {
        this.control({
            "#loginbutton": {
                click: this.onLoginbuttonClick
            },
            "#registerbutton": {
                click: this.onRegisterbuttonClick
            }
        });
    }

});
