/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W3D5_Project.view.MainViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    id: 'MainViewport',
    itemId: 'MainViewport',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'menu',
                    floating: false,
                    id: 'CategoriesMenu',
                    itemId: 'CategoriesMenu',
                    width: 124,
                    collapseDirection: 'left',
                    collapsed: true,
                    collapsible: true,
                    title: 'Categories',
                    items: [
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 5,
                    width: 202,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'tabpanel',
                            flex: 1,
                            id: 'MenuPanel',
                            itemId: 'MenuPanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 547,
                                    id: 'MenuTab1',
                                    itemId: 'MenuTab1',
                                    title: 'All Books',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            dock: 'top',
                                            height: 172,
                                            id: 'SearchPanel',
                                            itemId: 'SearchPanel',
                                            bodyPadding: 10,
                                            title: 'Search',
                                            layout: {
                                                type: 'vbox',
                                                align: 'center',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    id: 'SearchBox',
                                                    itemId: 'SearchBox',
                                                    width: 434,
                                                    fieldLabel: '',
                                                    emptyText: 'Search Title',
                                                    displayField: 'bookName',
                                                    store: 'SearchStore',
                                                    valueField: 'bookId'
                                                }
                                            ]
                                        }
                                    ],
                                    items: [
                                        {
                                            xtype: 'form',
                                            flex: 2,
                                            id: 'GenreAll',
                                            itemId: 'GenreAll',
                                            layout: 'fit',
                                            bodyPadding: 10,
                                            title: 'All Books',
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    id: 'BooksGrid',
                                                    itemId: 'BooksGrid',
                                                    title: '',
                                                    store: 'BookStore',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 242,
                                                            align: 'center',
                                                            dataIndex: 'bookTitle',
                                                            text: 'Title'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                                return '<img src="resources/img/' + value + '" align="center"/>';
                                                            },
                                                            width: 189,
                                                            resizable: false,
                                                            align: 'center',
                                                            dataIndex: 'bookImg',
                                                            text: 'Cover'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 209,
                                                            align: 'center',
                                                            dataIndex: 'bookAuthor',
                                                            text: 'Author'
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        formBind: false,
                                                        enableTextSelection: true
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'MenuTab2',
                                    itemId: 'MenuTab2',
                                    title: 'Best Seller'
                                },
                                {
                                    xtype: 'panel',
                                    id: 'MenuTab3',
                                    itemId: 'MenuTab3',
                                    title: 'On Sale'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});