/*
 * File: app/view/RegisterViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W3D5_Project.view.RegisterViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    height: 557,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'form',
                            height: 382,
                            width: 424,
                            bodyPadding: 10,
                            title: 'Register',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'RegFname',
                                    itemId: 'RegFname',
                                    fieldLabel: 'First Name'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 0,
                                    id: 'RegLname',
                                    itemId: 'RegLname',
                                    fieldLabel: 'Last Name'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 0,
                                    id: 'RegEmail',
                                    itemId: 'RegEmail',
                                    fieldLabel: 'Email'
                                },
                                {
                                    xtype: 'textareafield',
                                    flex: 0,
                                    id: 'RegAddress',
                                    itemId: 'regaddress',
                                    width: 285,
                                    fieldLabel: 'Billing Address'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 0,
                                    id: 'RegUsername',
                                    itemId: 'RegUsername',
                                    fieldLabel: 'User Name'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 0,
                                    id: 'RegPassword',
                                    itemId: 'RegPassword',
                                    fieldLabel: 'Password',
                                    inputType: 'password'
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 14,
                                    width: 10
                                },
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    height: 31,
                                    width: 280,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            id: 'RegBtn',
                                            itemId: 'RegBtn',
                                            width: 280,
                                            text: 'Register Now!'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});