/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Register.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'Register.view.MyViewportViewModel',
        'Ext.panel.Panel',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.TextArea',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    viewModel: {
        type: 'myviewport'
    },

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'panel',
            height: 425,
            width: 327,
            title: 'HomeWork',
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'container',
                    height: 374,
                    width: 312,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            width: 269,
                            fieldLabel: 'First Name'
                        },
                        {
                            xtype: 'textfield',
                            width: 263,
                            fieldLabel: 'Last Name:'
                        },
                        {
                            xtype: 'radiogroup',
                            width: 277,
                            fieldLabel: 'Gender',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    boxLabel: 'Male'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: 'Female'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            width: 272,
                            fieldLabel: 'Age'
                        },
                        {
                            xtype: 'textareafield',
                            flex: 0,
                            height: 62,
                            width: 273,
                            fieldLabel: 'Address:'
                        },
                        {
                            xtype: 'datefield',
                            flex: 0,
                            fieldLabel: 'Birthdate'
                        },
                        {
                            xtype: 'textfield',
                            flex: 0,
                            width: 277,
                            fieldLabel: 'User Name'
                        },
                        {
                            xtype: 'textfield',
                            flex: 0,
                            fieldLabel: 'Password'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 0,
                                    text: 'Register Now!'
                                },
                                {
                                    xtype: 'tbspacer'
                                },
                                {
                                    xtype: 'button',
                                    flex: 0,
                                    text: 'Log in'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});