/*
 * File: app/view/OrderWin.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W3D5_Project.view.OrderWin', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.container.Container',
        'Ext.Img',
        'Ext.form.field.Hidden',
        'Ext.form.field.Display',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    height: 536,
    width: 462,
    closeAction: 'hide',
    title: 'Order',
    modal: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 244,
                            id: 'BookWinImg',
                            itemId: 'BookWinImg',
                            width: 201
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            width: 314,
                            autoScroll: true,
                            items: [
                                {
                                    xtype: 'hiddenfield',
                                    id: 'BookWinId',
                                    itemId: 'BookWinId',
                                    fieldLabel: 'Title',
                                    value: 'Book Title'
                                },
                                {
                                    xtype: 'displayfield',
                                    id: 'BookWinTitle',
                                    itemId: 'BookWinTitle',
                                    fieldLabel: 'Title',
                                    value: 'Book Title'
                                },
                                {
                                    xtype: 'displayfield',
                                    id: 'BookWinAuthor',
                                    itemId: 'BookWinAuthor',
                                    fieldLabel: 'Author',
                                    value: 'Book Author'
                                },
                                {
                                    xtype: 'displayfield',
                                    id: 'BookWinDate',
                                    itemId: 'BookWinDate',
                                    fieldLabel: 'Publish Date',
                                    value: '01/01/2001'
                                },
                                {
                                    xtype: 'displayfield',
                                    id: 'BookWinDesc',
                                    itemId: 'BookWinDesc',
                                    fieldLabel: 'Description',
                                    value: 'This is a book'
                                },
                                {
                                    xtype: 'displayfield',
                                    id: 'BookWinPrice',
                                    itemId: 'BookWinPrice',
                                    fieldLabel: 'Price',
                                    value: 'USD 50.00'
                                }
                            ]
                        },
                        {
                            xtype: 'displayfield',
                            flex: 0,
                            id: 'BookWinBest',
                            itemId: 'BookWinBest',
                            fieldLabel: '',
                            value: 'Best Seller'
                        },
                        {
                            xtype: 'container',
                            flex: 0,
                            height: 51,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'CheckBtn',
                                    width: 100,
                                    text: 'Check-out'
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1,
                                    width: 45
                                },
                                {
                                    xtype: 'button',
                                    id: 'BuyBtn',
                                    width: 100,
                                    text: 'Buy'
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1,
                                    width: 45
                                },
                                {
                                    xtype: 'button',
                                    id: 'CancelBtn',
                                    width: 100,
                                    text: 'Cancel'
                                }
                            ]
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 0,
                            height: 10,
                            width: 10
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});