CREATE TABLE USERS
  (
    USER_ID    NUMBER NOT NULL ,
    FIRST_NAME VARCHAR2(20) ,
    LAST_NAME  VARCHAR2(20) ,
    CONSTRAINT USERS_PK PRIMARY KEY ( USER_ID )
  );
CREATE TABLE ORDERS
  (
    ORDER_ID   NUMBER NOT NULL ,
    ORDER_DATE DATE ,
    USER_ID    NUMBER ,
    CONSTRAINT ORDERS_PK PRIMARY KEY ( ORDER_ID ),
    CONSTRAINT ORDERS_USER_ID_FK FOREIGN KEY ( USER_ID ) REFERENCES USERS( USER_ID )
  );
CREATE TABLE ORDER_ITEMS
  (
    ORDER_ITEM_ID       NUMBER NOT NULL ,
    ORDER_ID            NUMBER ,
    ORDER_ITEM_NAME     VARCHAR2(20) ,
    ORDER_ITEM_QUANTITY NUMBER ,
    CONSTRAINT ORDER_ITEMS_PK PRIMARY KEY ( ORDER_ITEM_ID ),
    CONSTRAINT ORDER_ITEMS_ORDER_ID_FK FOREIGN KEY ( ORDER_ID ) REFERENCES ORDERS( ORDER_ID )
  );