Insert into STUDENT (STUDENT_ID,STUDENT_NAME,STUDENT_SCORE,STUDENT_TEACHERID) values ('1','Student 1',90,'1');
Insert into STUDENT (STUDENT_ID,STUDENT_NAME,STUDENT_SCORE,STUDENT_TEACHERID) values ('2','Student 2',70,'1');
Insert into STUDENT (STUDENT_ID,STUDENT_NAME,STUDENT_SCORE,STUDENT_TEACHERID) values ('3','Student 3',60,'2');
Insert into STUDENT (STUDENT_ID,STUDENT_NAME,STUDENT_SCORE,STUDENT_TEACHERID) values ('4','Student 4',97,'1');
Insert into STUDENT (STUDENT_ID,STUDENT_NAME,STUDENT_SCORE,STUDENT_TEACHERID) values ('5','Student 5',87,'2');
