--ITEM 1
SELECT * FROM EMP WHERE SAL > 3000;

--ITEM 2
SELECT * FROM EMP WHERE ENAME LIKE 'S%';

--ITEM 3
SELECT * FROM EMP WHERE ENAME IN ('SMITH','ALLEN','FORD');

--ITEM 4
SELECT A.* FROM EMP A, DEPT B WHERE A.DEPTNO = B.DEPTNO AND B.DNAME = 'SALES'

--ITEM 5
SELECT
  TO_CHAR(AVG(SAL),'FM9999999.00') AS "AVERAGE",
  MAX(SAL) AS "MAXIMUM",
  MIN(SAL) AS "MINIMUM",
  SUM(SAL) AS "TOTAL",
  DEPTNO
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO
--ITEM 6
SELECT COUNT(ENAME) FROM EMP WHERE SAL >3000 GROUP BY DEPTNO;

--ITEM 7
SELECT TO_CHAR(A.VALUE,'FM9999999.00') AS "VALUE",B.DNAME
FROM(SELECT AVG(SAL) AS "VALUE", DEPTNO FROM EMP GROUP BY DEPTNO) A, DEPT B
WHERE A.DEPTNO = B.DEPTNO
ORDER BY DNAME;

--ITEM 8 department number, salary, and number of employees.
SELECT C.DNAME, A.SAL, COUNT(A.ENAME) AS "NUMBER OF EMPLOYEES"
FROM EMP A, EMP B, DEPT C
WHERE A.SAL = B.SAL
AND A.ENAME != B.ENAME
AND A.DEPTNO = C.DEPTNO
GROUP BY C.DNAME,A.SAL

--ITEM 9
SELECT DISTINCT DNAME, LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP HAVING COUNT(ENAME) > 2 GROUP BY DEPTNO);

--ITEM 10
SELECT ENAME, SAL FROM EMP WHERE SAL > (SELECT AVG(SAL) FROM EMP);