/*
 * File: app/controller/AdminMgmtController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W5D5_Project.controller.AdminMgmtController', {
    extend: 'Ext.app.Controller',

    id: 'adminMgmtController',

    control: {
        "#adminUserMgmtBtn": {
            click: 'onAdminUserMgmtBtnClick'
        },
        "#adminProdMgmtBtn": {
            click: 'onAdminProdMgmtBtnClick'
        },
        "#adminOnlineUsersBtn": {
            click: 'onAdminOnlineUsersBtnClick'
        },
        "#adminOrderMgmtBtn": {
            click: 'onAdminOrderMgmtBtnClick'
        }
    },

    onAdminUserMgmtBtnClick: function() {
        Ext.getCmp('userMgmtTab').show();
        Ext.getCmp('prodMgmtTab').hide();
        Ext.getCmp('orderMgmtTab').hide();
        Ext.getCmp('onlineUsersTab').hide();
        Ext.Ajax.request({
            url : "getAllUsers",
            method : "GET",
            async : false,
            callback : function(options,success,response){
                if (Ext.isEmpty(response.responseText)) {
                    Ext.Msg.alert("Users",
                                  "Error in getting users");
                } else {
                    var userStore = Ext.getStore('UserStore');
                    var jsonResponse = Ext.JSON.decode(response.responseText);
                    userStore.loadData(jsonResponse);
                }
            }
        });
    },

    onAdminProdMgmtBtnClick: function() {
        Ext.getCmp('userMgmtTab').hide();
        Ext.getCmp('prodMgmtTab').show();
        Ext.getCmp('orderMgmtTab').hide();
        Ext.getCmp('onlineUsersTab').hide();
        Ext.Ajax.request({
            url : "getAllProducts",
            method : "GET",
            async : false,
            callback : function(options,success,response){
                if (Ext.isEmpty(response.responseText)) {
                    Ext.Msg.alert("Products",
                                  "Error in getting products");
                } else {
                    var prodStore = Ext.getStore('ProductStore');
                    var jsonResponse = Ext.JSON.decode(response.responseText);
                    prodStore.loadData(jsonResponse);
                }
            }
        });
    },

    onAdminOnlineUsersBtnClick: function() {
        Ext.getCmp('userMgmtTab').hide();
        Ext.getCmp('prodMgmtTab').hide();
        Ext.getCmp('orderMgmtTab').hide();
        Ext.getCmp('onlineUsersTab').show();

    },

    onAdminOrderMgmtBtnClick: function() {
        Ext.getCmp('userMgmtTab').hide();
        Ext.getCmp('prodMgmtTab').hide();
        Ext.getCmp('orderMgmtTab').show();
        Ext.getCmp('onlineUsersTab').hide();

    }

});
