/*
 * File: app/controller/BrowseProductController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W5D5_Project.controller.BrowseProductController', {
    extend: 'Ext.app.Controller',

    control: {
        "#browseProductsField": {
            change: 'onBrowseProductsSearchChange'
        },
        "#showBrowseBtn": {
            click: 'onBrowseProductClick'
        }
    },

    onBrowseProductsSearchChange: function(field, newValue, oldValue, eOpts) {
        var productSearch, prodStore;
        productSearch = Ext.getCmp('browseProductsField').getValue();
        prodStore = Ext.getStore('ProductStore');

        if(Ext.isEmpty(productSearch)){
            prodStore.clearFilter();
        } else{
            prodStore.filter('prodName',productSearch);
        }
    },

    onBrowseProductClick: function(button, e, eOpts) {
                                    Ext.Ajax.request({
                                        url : "getAllProducts",
                                        method : "GET",
                                        async : false,
                                        callback : function(options,success,response){
                                            if (Ext.isEmpty(response.responseText)) {
                                                Ext.Msg.alert("Products",
                                                              "Error in retrieving products");
                                            } else {
                                                var prodStore = Ext.getStore('ProductStore');
                                                var jsonResponse = Ext.JSON.decode(response.responseText);
                                                prodStore.loadData(jsonResponse);
                                            }
                                        }
                                    });

        var browseProductWindow = Ext.create('W5D5_Project.view.BrowseProductsWin');
        browseProductWindow.show();
        Ext.getCmp('browseProductsGrid').getView().refresh();
    }

});
