/*
 * File: app/store/SPStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W5D5_Project.store.SPStore', {
    extend: 'Ext.data.Store',

    requires: [
        'W5D5_Project.model.SPModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'SPStore',
            model: 'W5D5_Project.model.SPModel',
            data: [
                {
                    CountryName: 'Afghanistan',
                    SP: 'Badakhshan'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Badghis'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Baghlan'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Balkh'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Bamian'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Farah'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Faryab'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Ghazni'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Ghowr'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Helmand'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Herat'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Jowzjan'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Kabol'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Kandahar'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Kapisa'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Konar'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Kondoz'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Laghman'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Lowgar'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Nangarhar'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Nimruz'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Oruzgan'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Paktia'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Paktika'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Parvan'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Samangan'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Sar-e Pol'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Takhar'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Vardak'
                },
                {
                    CountryName: 'Afghanistan',
                    SP: 'Zabol'
                },
                {
                    CountryName: 'Austria',
                    SP: 'Burgenland'
                },
                {
                    CountryName: 'Austria',
                    SP: 'Kaernten'
                },
                {
                    CountryName: 'Austria',
                    SP: 'Niederoesterreich'
                },
                {
                    CountryName: 'Austria',
                    SP: 'Oberoesterreich'
                },
                {
                    CountryName: 'Austria',
                    SP: 'Salzburg'
                },
                {
                    CountryName: 'Austria',
                    SP: 'Steiermark'
                },
                {
                    CountryName: 'Austria',
                    SP: 'Tirol'
                },
                {
                    CountryName: 'Austria',
                    SP: 'Vorarlberg'
                },
                {
                    CountryName: 'Austria',
                    SP: 'Wien'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'Antwerpen'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'Brabant Wallon'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'Brussels Capitol Region'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'Hainaut'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'Liege'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'Limburg'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'Luxembourg'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'Namur'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'Oost-Vlaanderen'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'Vlaams Brabant'
                },
                {
                    CountryName: 'Belguim',
                    SP: 'West-Vlaanderen'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Banteay Mean Cheay'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Batdambang'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Kampong Cham'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Kampong Chhnang'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Kampong Spoe'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Kampong Thum'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Kampot'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Kandal'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Kaoh Kong'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Keb'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Kracheh'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Mondol Kiri'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Otdar Mean Cheay'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Pailin'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Phnum Penh'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Pouthisat'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Preah Seihanu (Sihanoukville)'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Preah Vihear'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Prey Veng'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Rotanah Kiri'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Siem Reab'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Stoeng Treng'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Svay Rieng'
                },
                {
                    CountryName: 'Cambodia',
                    SP: 'Takev'
                },
                {
                    CountryName: 'China',
                    SP: 'Anhui'
                },
                {
                    CountryName: 'China',
                    SP: 'Beijing'
                },
                {
                    CountryName: 'China',
                    SP: 'Chongqing'
                },
                {
                    CountryName: 'China',
                    SP: 'Fujian'
                },
                {
                    CountryName: 'China',
                    SP: 'Gansu'
                },
                {
                    CountryName: 'China',
                    SP: 'Guangdong'
                },
                {
                    CountryName: 'China',
                    SP: 'Guangxi'
                },
                {
                    CountryName: 'China',
                    SP: 'Guizhou'
                },
                {
                    CountryName: 'China',
                    SP: 'Hainan'
                },
                {
                    CountryName: 'China',
                    SP: 'Hebei'
                },
                {
                    CountryName: 'China',
                    SP: 'Heilongjiang'
                },
                {
                    CountryName: 'China',
                    SP: 'Henan'
                },
                {
                    CountryName: 'China',
                    SP: 'Hubei'
                },
                {
                    CountryName: 'China',
                    SP: 'Hunan'
                },
                {
                    CountryName: 'China',
                    SP: 'Jiangsu'
                },
                {
                    CountryName: 'China',
                    SP: 'Jiangxi'
                },
                {
                    CountryName: 'China',
                    SP: 'Jilin'
                },
                {
                    CountryName: 'China',
                    SP: 'Liaoning'
                },
                {
                    CountryName: 'China',
                    SP: 'Nei Mongol'
                },
                {
                    CountryName: 'China',
                    SP: 'Ningxia'
                },
                {
                    CountryName: 'China',
                    SP: 'Qinghai'
                },
                {
                    CountryName: 'China',
                    SP: 'Shaanxi'
                },
                {
                    CountryName: 'China',
                    SP: 'Shandong'
                },
                {
                    CountryName: 'China',
                    SP: 'Shanghai'
                },
                {
                    CountryName: 'China',
                    SP: 'Shanxi'
                },
                {
                    CountryName: 'China',
                    SP: 'Sichuan'
                },
                {
                    CountryName: 'China',
                    SP: 'Tianjin'
                },
                {
                    CountryName: 'China',
                    SP: 'Xinjiang'
                },
                {
                    CountryName: 'China',
                    SP: 'Xizang (Tibet)'
                },
                {
                    CountryName: 'China',
                    SP: 'Yunnan'
                },
                {
                    CountryName: 'China',
                    SP: 'Zhejiang'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Amazonas'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Antioquia'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Arauca'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Atlantico'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Bolivar'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Boyaca'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Caldas'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Caqueta'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Casanare'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Cauca'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Cesar'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Choco'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Cordoba'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Cundinamarca'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Distrito Capital de Santa Fe de Bogota'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Guainia'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Guaviare'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Huila'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'La Guajira'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Magdalena'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Meta'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Narino'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Norte de Santander'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Putumayo'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Quindio'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Risaralda'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'San Andres y Providencia'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Santander'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Sucre'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Tolima'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Valle del Cauca'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Vaupes'
                },
                {
                    CountryName: 'Colombia',
                    SP: 'Vichada'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Bjelovarsko-Bilogorska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Brodsko-Posavska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Dubrovacko-Neretvanska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Istarska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Karlovacka Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Koprivnicko-Krizevacka Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Krapinsko-Zagorska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Licko-Senjska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Medimurska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Osjecko-Baranjska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Pozesko-Slavonska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Primorsko-Goranska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Sibensko-Kninska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Sisacko-Moslavacka Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Splitsko-Dalmatinska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Varazdinska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Viroviticko-Podravska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Vukovarsko-Srijemska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Zadarska Zupanija'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Zagreb'
                },
                {
                    CountryName: 'Croatia',
                    SP: 'Zagrebacka Zupanija'
                },
                {
                    CountryName: 'France',
                    SP: 'Alsace'
                },
                {
                    CountryName: 'France',
                    SP: 'Aquitaine'
                },
                {
                    CountryName: 'France',
                    SP: 'Auvergne'
                },
                {
                    CountryName: 'France',
                    SP: 'Basse-Normandie'
                },
                {
                    CountryName: 'France',
                    SP: 'Bourgogne'
                },
                {
                    CountryName: 'France',
                    SP: 'Bretagne'
                },
                {
                    CountryName: 'France',
                    SP: 'Centre'
                },
                {
                    CountryName: 'France',
                    SP: 'Champagne-Ardenne'
                },
                {
                    CountryName: 'France',
                    SP: 'Corse'
                },
                {
                    CountryName: 'France',
                    SP: 'Franche-Comte'
                },
                {
                    CountryName: 'France',
                    SP: 'Haute-Normandie'
                },
                {
                    CountryName: 'France',
                    SP: 'Ile-de-France'
                },
                {
                    CountryName: 'France',
                    SP: 'Languedoc-Roussillon'
                },
                {
                    CountryName: 'France',
                    SP: 'Limousin'
                },
                {
                    CountryName: 'France',
                    SP: 'Lorraine'
                },
                {
                    CountryName: 'France',
                    SP: 'Midi-Pyrenees'
                },
                {
                    CountryName: 'France',
                    SP: 'Nord-Pas-de-Calais'
                },
                {
                    CountryName: 'France',
                    SP: 'Pays de la Loire'
                },
                {
                    CountryName: 'France',
                    SP: 'Picardie'
                },
                {
                    CountryName: 'France',
                    SP: 'Poitou-Charentes'
                },
                {
                    CountryName: 'France',
                    SP: 'Provence-Alpes-Cote d Azur'
                },
                {
                    CountryName: 'France',
                    SP: 'Rhone-Alpes'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Aichi'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Akita'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Aomori'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Chiba'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Ehime'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Fukui'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Fukuoka'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Fukushima'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Gifu'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Gumma'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Hiroshima'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Hokkaido'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Hyogo'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Ibaraki'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Ishikawa'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Iwate'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Kagawa'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Kagoshima'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Kanagawa'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Kochi'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Kumamoto'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Kyoto'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Mie'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Miyagi'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Miyazaki'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Nagano'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Nagasaki'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Nara'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Niigata'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Oita'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Okayama'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Okinawa'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Osaka'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Saga'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Saitama'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Shiga'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Shimane'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Shizuoka'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Tochigi'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Tokushima'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Tokyo'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Tottori'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Toyama'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Wakayama'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Yamagata'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Yamaguchi'
                },
                {
                    CountryName: 'Japan',
                    SP: 'Yamanashi'
                },
                {
                    CountryName: 'Macau',
                    SP: 'Macau'
                },
                {
                    CountryName: 'Madagascar',
                    SP: 'Antananarivo'
                },
                {
                    CountryName: 'Madagascar',
                    SP: 'Antsiranana'
                },
                {
                    CountryName: 'Madagascar',
                    SP: 'Fianarantsoa'
                },
                {
                    CountryName: 'Madagascar',
                    SP: 'Mahajanga'
                },
                {
                    CountryName: 'Madagascar',
                    SP: 'Toamasina'
                },
                {
                    CountryName: 'Madagascar',
                    SP: 'Toliara'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Johor'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Kedah'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Kelantan'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Labuan'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Melaka'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Negeri Sembilan'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Pahang'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Perak'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Perlis'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Pulau Pinang'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Sabah'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Sarawak'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Selangor'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Terengganu'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Wilayah Persekutuan'
                },
                {
                    CountryName: 'Malaysia',
                    SP: 'Wilayah Persekutuan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Abra'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Agusan del Norte'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Agusan del Sur'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Aklan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Albay'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Angeles'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Antique'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Aurora'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Bacolod'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Bago'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Baguio'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Bais'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Basilan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Basilan City'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Bataan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Batanes'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Batangas'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Batangas City'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Benguet'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Bohol'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Bukidnon'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Bulacan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Butuan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Cabanatuan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Cadiz'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Cagayan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Cagayan de Oro'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Calbayog'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Caloocan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Camarines Norte'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Camarines Sur'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Camiguin'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Canlaon'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Capiz'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Catanduanes'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Cavite'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Cavite City'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Cebu'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Cebu City'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Cotabato'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Dagupan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Danao'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Dapitan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Davao City Davao'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Davao del Sur'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Davao Oriental'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Dipolog'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Dumaguete'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Eastern Samar'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'General Santos'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Gingoog'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Ifugao'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Iligan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Ilocos Norte'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Ilocos Sur'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Iloilo'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Iloilo City'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Iriga'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Isabela'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Kalinga-Apayao'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'La Carlota'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'La Union'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Laguna'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Lanao del Norte'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Lanao del Sur'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Laoag'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Lapu-Lapu'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Legaspi'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Leyte'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Lipa'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Lucena'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Maguindanao'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Mandaue'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Manila'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Marawi'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Marinduque'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Masbate'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Mindoro Occidental'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Mindoro Oriental'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Misamis Occidental'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Misamis Oriental'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Mountain'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Naga'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Negros Occidental'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Negros Oriental'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'North Cotabato'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Northern Samar'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Nueva Ecija'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Nueva Vizcaya'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Olongapo'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Ormoc'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Oroquieta'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Ozamis'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Pagadian'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Palawan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Palayan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Pampanga'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Pangasinan'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Pasay'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Puerto Princesa'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Quezon'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Quezon City'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Quirino'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Rizal'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Romblon'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Roxas'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Samar'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'San Carlos (in Negros Occidental)'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'San Carlos (in Pangasinan)'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'San Jose'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'San Pablo'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Silay'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Siquijor'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Sorsogon'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'South Cotabato'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Southern Leyte'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Sultan Kudarat'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Sulu'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Surigao'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Surigao del Norte'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Surigao del Sur'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Tacloban'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Tagaytay'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Tagbilaran'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Tangub'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Tarlac'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Tawitawi'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Toledo'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Trece Martires'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Zambales'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Zamboanga'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Zamboanga del Norte'
                },
                {
                    CountryName: 'Philippines',
                    SP: 'Zamboanga del Sur'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Dolnoslaskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Kujawsko-Pomorskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Lodzkie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Lubelskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Lubuskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Malopolskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Mazowieckie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Opolskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Podkarpackie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Podlaskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Pomorskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Slaskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Swietokrzyskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Warminsko-Mazurskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Wielkopolskie'
                },
                {
                    CountryName: 'Poland',
                    SP: 'Zachodniopomorskie'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Acores (Azores)'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Aveiro'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Beja'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Braga'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Braganca'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Castelo Branco'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Coimbra'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Evora'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Faro'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Guarda'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Leiria'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Lisboa'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Madeira'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Portalegre'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Porto'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Santarem'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Setubal'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Viana do Castelo'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Vila Real'
                },
                {
                    CountryName: 'Portugal',
                    SP: 'Viseu'
                },
                {
                    CountryName: 'Singapore',
                    SP: 'Singapore'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Blekinge'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Dalarnas'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Gavleborgs'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Gotlands'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Hallands'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Jamtlands'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Jonkopings'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Kalmar'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Kronobergs'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Norrbottens'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Orebro'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Ostergotlands'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Skane'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Sodermanlands'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Stockholms'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Uppsala'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Varmlands'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Vasterbottens'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Vasternorrlands'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Vastmanlands'
                },
                {
                    CountryName: 'Sweden',
                    SP: 'Vastra Gotalands'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Chang-hua'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Chi-lung'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Chia-i'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Chia-i'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Chung-hsing-hsin-ts un'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Hsin-chu'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Hsin-chu'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Hua-lien'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'I-lan'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Kao-hsiung'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Kao-hsiung'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Miao-li'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Nan-t ou'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'P eng-hu'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'P ing-tung'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'T ai-chung'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'T ai-chung'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'T ai-nan'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'T ai-nan'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'T ai-pei'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'T ai-pei'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'T ai-tung'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'T ao-yuan'
                },
                {
                    CountryName: 'Taiwan',
                    SP: 'Yun-lin'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Amnat Charoen'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Ang Thong'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Buriram'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Chachoengsao'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Chai Nat'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Chaiyaphum'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Chanthaburi'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Chiang Mai'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Chiang Rai'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Chon Buri'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Chumphon'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Kalasin'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Kamphaeng Phet'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Kanchanaburi'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Khon Kaen'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Krabi'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Krung Thep Mahanakhon (Bangkok)'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Lampang'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Lamphun'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Loei'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Lop Buri'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Mae Hong Son'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Maha Sarakham'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Mukdahan'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Nakhon Nayok'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Nakhon Pathom'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Nakhon Phanom'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Nakhon Ratchasima'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Nakhon Sawan'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Nakhon Si Thammarat'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Nan'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Narathiwat'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Nong Bua Lamphu'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Nong Khai'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Nonthaburi'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Pathum Thani'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Pattani'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Phangnga'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Phatthalung'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Phayao'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Phetchabun'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Phetchaburi'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Phichit'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Phitsanulok'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Phra Nakhon Si Ayutthaya'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Phrae'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Phuket'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Prachin Buri'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Prachuap Khiri Khan'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Ranong'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Ratchaburi'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Rayong'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Roi Et'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Sa Kaeo'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Sakon Nakhon'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Samut Prakan'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Samut Sakhon'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Samut Songkhram'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Sara Buri'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Satun'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Sing Buri'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Sisaket'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Songkhla'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Sukhothai'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Suphan Buri'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Surat Thani'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Surin'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Tak'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Trang'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Trat'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Ubon Ratchathani'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Udon Thani'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Uthai Thani'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Uttaradit'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Yala'
                },
                {
                    CountryName: 'Thailand',
                    SP: 'Yasothon'
                },
                {
                    CountryName: 'USA',
                    SP: 'Alabama'
                },
                {
                    CountryName: 'USA',
                    SP: 'Alaska'
                },
                {
                    CountryName: 'USA',
                    SP: 'Arizona'
                },
                {
                    CountryName: 'USA',
                    SP: 'Arkansas'
                },
                {
                    CountryName: 'USA',
                    SP: 'California'
                },
                {
                    CountryName: 'USA',
                    SP: 'Colorado'
                },
                {
                    CountryName: 'USA',
                    SP: 'Connecticut'
                },
                {
                    CountryName: 'USA',
                    SP: 'Delaware'
                },
                {
                    CountryName: 'USA',
                    SP: 'District of Columbia'
                },
                {
                    CountryName: 'USA',
                    SP: 'Florida'
                },
                {
                    CountryName: 'USA',
                    SP: 'Georgia'
                },
                {
                    CountryName: 'USA',
                    SP: 'Hawaii'
                },
                {
                    CountryName: 'USA',
                    SP: 'Idaho'
                },
                {
                    CountryName: 'USA',
                    SP: 'Illinois'
                },
                {
                    CountryName: 'USA',
                    SP: 'Indiana'
                },
                {
                    CountryName: 'USA',
                    SP: 'Iowa'
                },
                {
                    CountryName: 'USA',
                    SP: 'Kansas'
                },
                {
                    CountryName: 'USA',
                    SP: 'Kentucky'
                },
                {
                    CountryName: 'USA',
                    SP: 'Louisiana'
                },
                {
                    CountryName: 'USA',
                    SP: 'Maine'
                },
                {
                    CountryName: 'USA',
                    SP: 'Maryland'
                },
                {
                    CountryName: 'USA',
                    SP: 'Massachusetts'
                },
                {
                    CountryName: 'USA',
                    SP: 'Michigan'
                },
                {
                    CountryName: 'USA',
                    SP: 'Minnesota'
                },
                {
                    CountryName: 'USA',
                    SP: 'Mississippi'
                },
                {
                    CountryName: 'USA',
                    SP: 'Missouri'
                },
                {
                    CountryName: 'USA',
                    SP: 'Montana'
                },
                {
                    CountryName: 'USA',
                    SP: 'Nebraska'
                },
                {
                    CountryName: 'USA',
                    SP: 'Nevada'
                },
                {
                    CountryName: 'USA',
                    SP: 'New Hampshire'
                },
                {
                    CountryName: 'USA',
                    SP: 'New Jersey'
                },
                {
                    CountryName: 'USA',
                    SP: 'New Mexico'
                },
                {
                    CountryName: 'USA',
                    SP: 'New York'
                },
                {
                    CountryName: 'USA',
                    SP: 'North Carolina'
                },
                {
                    CountryName: 'USA',
                    SP: 'North Dakota'
                },
                {
                    CountryName: 'USA',
                    SP: 'Ohio'
                },
                {
                    CountryName: 'USA',
                    SP: 'Oklahoma'
                },
                {
                    CountryName: 'USA',
                    SP: 'Oregon'
                },
                {
                    CountryName: 'USA',
                    SP: 'Pennsylvania'
                },
                {
                    CountryName: 'USA',
                    SP: 'Rhode Island'
                },
                {
                    CountryName: 'USA',
                    SP: 'South Carolina'
                },
                {
                    CountryName: 'USA',
                    SP: 'South Dakota'
                },
                {
                    CountryName: 'USA',
                    SP: 'Tennessee'
                },
                {
                    CountryName: 'USA',
                    SP: 'Texas'
                },
                {
                    CountryName: 'USA',
                    SP: 'Utah'
                },
                {
                    CountryName: 'USA',
                    SP: 'Vermont'
                },
                {
                    CountryName: 'USA',
                    SP: 'Virginia'
                },
                {
                    CountryName: 'USA',
                    SP: 'Washington'
                },
                {
                    CountryName: 'USA',
                    SP: 'West Virginia'
                },
                {
                    CountryName: 'USA',
                    SP: 'Wisconsin'
                },
                {
                    CountryName: 'USA',
                    SP: 'Wyoming'
                }
            ]
        }, cfg)]);
    }
});