/*
 * File: app/controller/ProdInfoController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W5D5_Project.controller.ProdInfoController', {
    extend: 'Ext.app.Controller',

    control: {
        "#prodInfoCartBtn": {
            click: 'onProdInfoCartBtnClick'
        }
    },

    onProdInfoCartBtnClick: function() {
        var store = Ext.getStore('CartProductStore'),
            record = this.recordData,
            isExists = false,
            cartCount = Ext.getCmp('cartCount');
        Ext.each(store.data.items,function(rec){
            if(rec.data.prodId==record.prodId){
                rec.data.prodQty=parseInt(rec.data.prodQty)+1;
                rec.data.prodSubtotal=rec.data.prodSubtotal+rec.data.prodPrice;
                isExists = true;
                record=rec.data;
                Ext.getCmp('cartProductGrid').getView().refresh();
            }
        });
        if(!isExists){
            record.cartprodId='';
            record.prodQty=1;
            store.add(record);
        }
        Ext.Msg.alert('Status', 'Added item to cart');
        console.log(store);
        Ext.Ajax.request({
            url : 'addToCart',
            method : 'POST',
            params : {
                userId: Ext.getCmp('idField').getValue(),
                prodId: record.prodId,
                prodName: record.prodName,
                prodCat: record.prodCat,
                prodDesc: record.prodDesc,
                prodPrice: record.prodPrice,
                prodSale: record.prodSale,
                prodStock: record.prodStock,
                prodImg: record.prodImg,
                prodQty: record.prodQty,
                prodSubtotal: record.prodSubtotal
            },
            callback : function(options, success, response){
                if(!Ext.isEmpty(response.responseText)){
                    console.log("success!");
                }
            }
        });
    },

    showProdInfoWin: function(record) {
        this.recordData = record;
        if(Ext.isEmpty(this.prodInfoWin)){
            this.prodInfoWin = Ext.create('W5D5_Project.view.ProdInfoWin');
        }
        Ext.getCmp('prodInfoImg').setSrc('resources/img/' + record.prodImg + '.png');
        Ext.getCmp('prodInfoId').setValue(record.prodId);
        Ext.getCmp('prodInfoName').setValue(record.prodName);
        Ext.getCmp('prodInfoCat').setValue(record.prodCat);
        Ext.getCmp('prodInfoDesc').setValue(record.prodDesc);
        if(record.prodSale!=1){
            Ext.getCmp('prodInfoPrice').setValue(record.prodPrice * record.prodSale);
        }else{
            Ext.getCmp('prodInfoPrice').setValue(record.prodPrice);
        }
        Ext.getCmp('prodInfoAveRating').setValue(5);
        this.prodInfoWin.show();
    },

    hideProdInfoWin: function() {
        if(!Ext.isEmpty(this.prodInfoWin)){
            this.prodInfoWin.hide();
        }
    }

});
