DROP TABLE ORDERPRODUCT;
DROP TABLE PRODUCT;
DROP TABLE ORDERS;
DROP TABLE USERS;
DROP TABLE FAVORITEITEMS;
DROP TABLE CARTPRODUCT

CREATE TABLE USERS(
  USERID        NUMBER(3)     NOT NULL      PRIMARY KEY,
  USERFNAME         VARCHAR2(50),
  USERLNAME         VARCHAR2(50),
  USEREMAIL         VARCHAR2(50),
  USERPASS		    VARCHAR2(150),
  USEROCCUPATION	VARCHAR2(50),
  USERADDRESS1        VARCHAR2(100),
  USERADDRESS2        VARCHAR2(100),
  USERCITY          VARCHAR2(50),
  USERSP          VARCHAR2(100),
  USERCOUNTRY       VARCHAR2(50),
  USERTYPE          VARCHAR2(10),
  USERLEVEL			NUMBER(2)
);

CREATE TABLE PRODUCT(
  PRODID        NUMBER(3)     NOT NULL      PRIMARY KEY,
  PRODNAME      VARCHAR2(50),
  PRODCAT      VARCHAR2(50),
  PRODDESC			VARCHAR2(200),
  PRODPRICE         FLOAT,
  PRODSALE			NUMBER(3,2),
  PRODSTOCK         NUMBER(4),
  PRODIMG           VARCHAR2(50)
);

CREATE TABLE ORDERS(
  ORDERID       NUMBER(3)     NOT NULL      PRIMARY KEY,
  USERID        NUMBER(3),
  ORDERTOTAL         FLOAT,
  ORDERDATE      VARCHAR2(50)
);

CREATE TABLE ORDERPRODUCT(
  ORDERPRODID  NUMBER(3)     NOT NULL      PRIMARY KEY,
  ORDERID         NUMBER(3),
  PRODID          NUMBER(3),
  ORDERPRODQTY             NUMBER(4)
);

CREATE TABLE FAVORITEITEMS(
  FAVEITEMID		NUMBER(3)		NOT NULL		PRIMARY KEY,
  PRODID			NUMBER(3),
  USERID			NUMBER(3)
);

CREATE TABLE CARTPRODUCT(
  USERID			NUMBER(3)		NOT NULL,
  ORDERID			NUMBER(3)		NOT NULL,
  PRODID			NUMBER(3)		NOT NULL,
  PRODNAME      	VARCHAR2(50),
  PRODCAT      		VARCHAR2(50),
  PRODDESC			VARCHAR2(200),
  PRODPRICE         FLOAT,
  PRODSALE			FLOAT,
  PRODSTOCK         NUMBER(4),
  PRODIMG           VARCHAR2(50),
  PRODQTY			NUMBER(9),
  PRODSUBTOTAL		FLOAT,
  IS_DELETED		NUMBER(1)
);

--CREATE INDEX
CREATE UNIQUE INDEX user_index ON USERS (USEREMAIL);
CREATE UNIQUE INDEX prod_index ON PRODUCT (PRODNAME,PRODCAT,PRODDESC);
CREATE UNIQUE INDEX order_index ON ORDERS (USERID,ORDERDATE);
CREATE UNIQUE INDEX orderprod_index ON ORDERPRODUCT (ORDERID,PRODID);
CREATE UNIQUE INDEX faveitems_index ON FAVORITEITEMS (PRODID,USERID);
CREATE UNIQUE INDEX cartprod_index ON CARTPRODUCT (USERID,ORDERID,PRODID);