SELECT USERS_ID FROM USERS where USERS_FNAME = 'User Firstname 1'; 
SELECT USERS_FNAME, USERS_LNAME, ORDERS_ID  FROM USERS, ORDERS where USERS_FNAME = 'User Firstname 1'; 
SELECT ORDERITEM_NAME, ORDERITEM_DESRIPTION FROM ORDERITEM where ORDERITEM_PRICE > 100; 
