   INSERT INTO  USERS (USERS_ID, USERS_FNAME, USERS_LNAME, USERS_CONTACT, USERS_ADDRESS) VALUES (1, 'User Firstname 1', 'User Lastname 1', '123-45678', 'User Address 1');
   INSERT INTO  USERS (USERS_ID, USERS_FNAME, USERS_LNAME, USERS_CONTACT, USERS_ADDRESS) VALUES (2, 'User Firstname 2', 'User Lastname 2', '231-65487', 'User Address 2');
   INSERT INTO  USERS (USERS_ID, USERS_FNAME, USERS_LNAME, USERS_CONTACT, USERS_ADDRESS) VALUES (3, 'User Firstname 3', 'User Lastname 3', '321-87654', 'User Address 3');
   
   INSERT INTO ORDERITEM(ORDERITEM_ID, ORDERITEM_CUSTOMER, ORDERITEM_NAME, ORDERITEM_PRICE, ORDERITEM_DESCRIPTION, ORDERITEM_QUANTITY) VALUES (1, 1, 'Item 1', 100.00, 'Item Description 1', 5);
   INSERT INTO ORDERITEM(ORDERITEM_ID, ORDERITEM_CUSTOMER, ORDERITEM_NAME, ORDERITEM_PRICE, ORDERITEM_DESCRIPTION, ORDERITEM_QUANTITY) VALUES (2, 1, 'Item 2', 200.00, 'Item Description 2', 5);
   INSERT INTO ORDERITEM(ORDERITEM_ID, ORDERITEM_CUSTOMER, ORDERITEM_NAME, ORDERITEM_PRICE, ORDERITEM_DESCRIPTION, ORDERITEM_QUANTITY) VALUES (3, 2, 'Item 3', 100.00, 'Item Description 3', 5);   

   
   INSERT INTO ORDERS(ORDERS_ID, ORDERS_USERS, ORDERS_ITEMORDER,ORDERS_NUMBER,ORDERS_TOTAL) VALUES (1, 1, 1, 2, 200.00); 
   INSERT INTO ORDERS(ORDERS_ID, ORDERS_USERS, ORDERS_ITEMORDER,ORDERS_NUMBER,ORDERS_TOTAL) VALUES (2, 3, 2, 2, 400.00);
   