INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSALE,PRODSTOCK,PRODIMG) VALUES('IWC SCHAFFHAUSEN 1970','Casual','Sample Desc',1000,1,100,'casual1.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('IWC SCHAFFHAUSEN 1972','Casual','Sample Desc',1500,1,50,'casual2.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('TISSOT 1853','Casual','Sample Desc',1275,1,60,'casual3.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('BAUME & MERCIER GENEVE','Casual','Sample Desc',999.75,1,100,'casual4.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('CITIZEN ECO-DRIVE','Casual','Sample Desc',1000,1,10,'casual5.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('IWC SCHAFFHAUSEN MAR XVIII','Casual','Sample Desc',2000,1,90,'casual6.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('SWISS MOVADO QUARTZ','Casual','Sample Desc',500,0.75,25,'casual7.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('HAMILTON KHAKI AUTOMATIC','Casual','Sample Desc',1000,1,28,'casual8.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('HAMILTON KHAKI MECHANICAL','Casual','Sample Desc',1800,1,92,'casual9.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('DANIEL WELLINGTON','Casual','Sample Desc',1750,1,23,'casual10.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('RAYMOND WEIL GENEVE','Casual','Sample Desc',1499.75,0.5,46,'casual11.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('BREGUET','Casual','Sample Desc',2000,1,100,'casual12.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('IWC SCHAFFHAUSEN CHRONOGRAPH AUTOMATIC','Casual','Sample Desc',1875,0.5,10,'casual13.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('CITIZEN ECO-DRIVE C1','Casual','Sample Desc',1000,0.2,5,'casual14.png');

INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('NYC LOCAL','Digital','Sample Desc',2000,1,100,'digital1.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('NYC LOCAL 3','Digital','Sample Desc',3000,1,101,'digital2.png');

INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('CITIZEN ECO-DRIVE D1','Dress','Sample Desc',2000,1,50,'dress1.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('TISSOT 1857','Dress','Sample Desc',2500,0.75,25,'dress2.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('MARC BY MARC JACOBS','Dress','Sample Desc',2999.75,0.5,10,'dress.png');

INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('ROLEX SUBMARINER BLACK DIAL','Luxury','Sample Desc',5000,0.9,20,'luxury1.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('OMEGA SEAMASTER','Luxury','Sample Desc',8000,1,20,'luxury2.png');
INSERT INTO PRODUCT(PRODNAME,PRODCAT,PRODDESC,PRODPRICE,PRODSTOCK,PRODIMG) VALUES('MICHAEL KORS LEXINGTON','Luxury','Sample Desc',9000,1,5,'luxury3.png');
