CREATE TABLE W6D2_ITEM(
  ITEM_ID       VARCHAR2(100)       NOT NULL    PRIMARY KEY,
  ITEM_NAME     VARCHAR2(100),
  ITEM_CATEGORY VARCHAR2(100),
  ITEM_STOCK    NUMBER(9),
  ITEM_PRICE    NUMBER(11,2)
);

INSERT INTO W6D2_ITEM(ITEM_ID,ITEM_NAME,ITEM_CATEGORY,ITEM_STOCK,ITEM_PRICE) VALUES('1','ABC','Alphabet',20,99.75);
INSERT INTO W6D2_ITEM(ITEM_ID,ITEM_NAME,ITEM_CATEGORY,ITEM_STOCK,ITEM_PRICE) VALUES('2','123','Numbers',10,50.75);