--------------------------------------------------------
--  File created - Friday-June-24-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHAT_USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CHAT_USERS" 
   (	"USER_ID" NUMBER(3,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"ACTIVE" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHAT_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CHAT_USERS_PK" ON "SYSTEM"."CHAT_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CHAT_USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CHAT_USERS" ADD CONSTRAINT "CHAT_USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CHAT_USERS" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CHAT_USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CHAT_USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CHAT_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger CHAT_USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."CHAT_USERS_TRG" 
BEFORE INSERT ON CHAT_USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.USER_ID IS NULL THEN
      SELECT CHAT_USERS_SEQ.NEXTVAL INTO :NEW.USER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."CHAT_USERS_TRG" ENABLE;
