/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W3D5_Project.view.MainViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.form.FieldContainer',
        'Ext.form.field.Display',
        'Ext.toolbar.Spacer',
        'Ext.form.field.TextArea',
        'Ext.form.field.Checkbox'
    ],

    id: 'MainViewport',
    itemId: 'MainViewport',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'menu',
                    floating: false,
                    id: 'CategoriesMenu',
                    itemId: 'CategoriesMenu',
                    width: 124,
                    collapseDirection: 'left',
                    collapsed: true,
                    collapsible: true,
                    title: 'Categories',
                    items: [
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 5,
                    width: 202,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'tabpanel',
                            flex: 1,
                            id: 'MenuPanel',
                            itemId: 'MenuPanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 547,
                                    id: 'MenuTab1',
                                    itemId: 'MenuTab1',
                                    title: 'All Books',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            dock: 'top',
                                            height: 172,
                                            id: 'SearchPanel',
                                            itemId: 'SearchPanel',
                                            bodyPadding: 10,
                                            title: 'Search',
                                            layout: {
                                                type: 'vbox',
                                                align: 'center',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    id: 'SearchBox',
                                                    itemId: 'SearchBox',
                                                    width: 599,
                                                    fieldLabel: '',
                                                    emptyText: 'Search Title',
                                                    displayField: 'title',
                                                    queryMode: 'local',
                                                    store: 'SearchStore',
                                                    valueField: 'id'
                                                }
                                            ]
                                        }
                                    ],
                                    items: [
                                        {
                                            xtype: 'form',
                                            flex: 2,
                                            id: 'GenreAll',
                                            itemId: 'GenreAll',
                                            layout: 'fit',
                                            bodyPadding: 10,
                                            title: 'All Books',
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    id: 'BooksGrid',
                                                    itemId: 'BooksGrid',
                                                    title: '',
                                                    store: 'BookStore',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 242,
                                                            align: 'center',
                                                            dataIndex: 'title',
                                                            text: 'Title'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                                return '<img src="resources/img/' + value + '" align="center"/>';
                                                            },
                                                            width: 189,
                                                            resizable: false,
                                                            align: 'center',
                                                            dataIndex: 'img',
                                                            text: 'Cover'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 209,
                                                            align: 'center',
                                                            dataIndex: 'author',
                                                            text: 'Author'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Desc',
                                                            itemId: 'Desc',
                                                            width: 171,
                                                            align: 'center',
                                                            dataIndex: 'desc',
                                                            text: 'Book Description'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Date',
                                                            itemId: 'Date',
                                                            align: 'center',
                                                            dataIndex: 'date',
                                                            text: 'Publish Date'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Price',
                                                            itemId: 'Price',
                                                            align: 'center',
                                                            dataIndex: 'oprice',
                                                            text: 'Price'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Avail',
                                                            itemId: 'Avail',
                                                            align: 'center',
                                                            dataIndex: 'avail',
                                                            text: '# of Available Copies'
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        formBind: false,
                                                        enableTextSelection: true
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'MenuTab2',
                                    itemId: 'MenuTab2',
                                    title: 'Best Seller',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            height: 397,
                                            id: 'BestBooks',
                                            itemId: 'BestBooks',
                                            bodyPadding: 10,
                                            title: 'Best Selling Books',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    height: 290,
                                                    id: 'BestBooksGrid',
                                                    itemId: 'BestBooksGrid',
                                                    title: '',
                                                    store: 'BookStore',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 242,
                                                            align: 'center',
                                                            dataIndex: 'title',
                                                            text: 'Title'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                                return '<img src="resources/img/' + value + '" align="center"/>';
                                                            },
                                                            width: 189,
                                                            resizable: false,
                                                            align: 'center',
                                                            dataIndex: 'img',
                                                            text: 'Cover'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 209,
                                                            align: 'center',
                                                            dataIndex: 'author',
                                                            text: 'Author'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Desc1',
                                                            itemId: 'Desc',
                                                            width: 171,
                                                            align: 'center',
                                                            dataIndex: 'desc',
                                                            text: 'Book Description'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Date1',
                                                            itemId: 'Date',
                                                            align: 'center',
                                                            dataIndex: 'date',
                                                            text: 'Publish Date'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Price1',
                                                            itemId: 'Price',
                                                            align: 'center',
                                                            dataIndex: 'oprice',
                                                            text: 'Price'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Avail1',
                                                            itemId: 'Avail',
                                                            align: 'center',
                                                            dataIndex: 'avail',
                                                            text: '# of Available Copies'
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        formBind: false,
                                                        enableTextSelection: true
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'MenuTab3',
                                    itemId: 'MenuTab3',
                                    title: 'On Sale',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            id: 'SaleBooks',
                                            itemId: 'SaleBooks',
                                            bodyPadding: 10,
                                            title: 'Books That Are On Sale',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    height: 290,
                                                    id: 'SaleBooksGrid',
                                                    itemId: 'SaleBooksGrid',
                                                    title: '',
                                                    store: 'BookStore',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 242,
                                                            align: 'center',
                                                            dataIndex: 'title',
                                                            text: 'Title'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                                return '<img src="resources/img/' + value + '" align="center"/>';
                                                            },
                                                            width: 189,
                                                            resizable: false,
                                                            align: 'center',
                                                            dataIndex: 'img',
                                                            text: 'Cover'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 209,
                                                            align: 'center',
                                                            dataIndex: 'author',
                                                            text: 'Author'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Desc2',
                                                            itemId: 'Desc',
                                                            width: 171,
                                                            align: 'center',
                                                            dataIndex: 'desc',
                                                            text: 'Book Description'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Date2',
                                                            itemId: 'Date',
                                                            align: 'center',
                                                            dataIndex: 'date',
                                                            text: 'Publish Date'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Perc',
                                                            itemId: 'Perc',
                                                            align: 'center',
                                                            dataIndex: 'oprice',
                                                            text: '% Off'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Price2',
                                                            itemId: 'Price',
                                                            align: 'center',
                                                            dataIndex: 'oprice',
                                                            text: 'Original Price'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'SalePrice',
                                                            itemId: 'SalePrice',
                                                            align: 'center',
                                                            dataIndex: 'sprice',
                                                            text: 'Sale Price'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Avail2',
                                                            itemId: 'Avail',
                                                            align: 'center',
                                                            dataIndex: 'avail',
                                                            text: '# of Available Copies'
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        formBind: false,
                                                        enableTextSelection: true
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'MenuTab4',
                                    itemId: 'MenuTab4',
                                    title: 'Manage Users',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 0,
                                            height: 303,
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    height: 253,
                                                    width: 848,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'form',
                                                            flex: 0,
                                                            height: 253,
                                                            id: 'UsersForm',
                                                            itemId: 'UsersForm',
                                                            width: 1012,
                                                            bodyPadding: 10,
                                                            title: 'Manage Users',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'fieldcontainer',
                                                                    flex: 0,
                                                                    height: 245,
                                                                    width: 792,
                                                                    fieldLabel: 'User Info',
                                                                    layout: {
                                                                        type: 'hbox',
                                                                        align: 'stretch'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'container',
                                                                            flex: 0,
                                                                            height: 212,
                                                                            width: 268,
                                                                            layout: 'vbox',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'displayfield',
                                                                                    flex: 0,
                                                                                    id: 'id',
                                                                                    itemId: 'id',
                                                                                    width: 527,
                                                                                    fieldLabel: 'id',
                                                                                    value: ''
                                                                                },
                                                                                {
                                                                                    xtype: 'textfield',
                                                                                    flex: 0,
                                                                                    id: 'fname',
                                                                                    itemId: 'fname',
                                                                                    width: 267,
                                                                                    fieldLabel: 'First Name'
                                                                                },
                                                                                {
                                                                                    xtype: 'textfield',
                                                                                    flex: 0,
                                                                                    id: 'lname',
                                                                                    itemId: 'lname',
                                                                                    width: 266,
                                                                                    fieldLabel: 'Last Name'
                                                                                },
                                                                                {
                                                                                    xtype: 'textfield',
                                                                                    flex: 0,
                                                                                    id: 'email',
                                                                                    itemId: 'email',
                                                                                    width: 266,
                                                                                    fieldLabel: 'Email'
                                                                                },
                                                                                {
                                                                                    xtype: 'container',
                                                                                    flex: 0,
                                                                                    width: 275,
                                                                                    layout: {
                                                                                        type: 'hbox',
                                                                                        align: 'middle'
                                                                                    },
                                                                                    items: [
                                                                                        {
                                                                                            xtype: 'container',
                                                                                            flex: 0,
                                                                                            height: 89,
                                                                                            width: 106,
                                                                                            layout: 'vbox',
                                                                                            items: [
                                                                                                {
                                                                                                    xtype: 'container',
                                                                                                    flex: 0,
                                                                                                    height: 30,
                                                                                                    items: [
                                                                                                        {
                                                                                                            xtype: 'button',
                                                                                                            height: 22,
                                                                                                            id: 'UserCreate',
                                                                                                            itemId: 'UserCreate',
                                                                                                            width: 91,
                                                                                                            text: 'Create'
                                                                                                        }
                                                                                                    ]
                                                                                                },
                                                                                                {
                                                                                                    xtype: 'container',
                                                                                                    flex: 0,
                                                                                                    height: 24,
                                                                                                    width: 93,
                                                                                                    items: [
                                                                                                        {
                                                                                                            xtype: 'button',
                                                                                                            id: 'UserUpdate',
                                                                                                            width: 92,
                                                                                                            text: 'Update'
                                                                                                        }
                                                                                                    ]
                                                                                                },
                                                                                                {
                                                                                                    xtype: 'container',
                                                                                                    flex: 1,
                                                                                                    items: [
                                                                                                        {
                                                                                                            xtype: 'button',
                                                                                                            id: 'UserDelete',
                                                                                                            itemId: 'UserDelete',
                                                                                                            width: 93,
                                                                                                            text: 'Delete'
                                                                                                        }
                                                                                                    ]
                                                                                                }
                                                                                            ]
                                                                                        },
                                                                                        {
                                                                                            xtype: 'container',
                                                                                            width: 13,
                                                                                            items: [
                                                                                                {
                                                                                                    xtype: 'tbspacer',
                                                                                                    height: 73,
                                                                                                    width: 21
                                                                                                }
                                                                                            ]
                                                                                        },
                                                                                        {
                                                                                            xtype: 'container',
                                                                                            flex: 0,
                                                                                            layout: 'fit',
                                                                                            items: [
                                                                                                {
                                                                                                    xtype: 'container',
                                                                                                    items: [
                                                                                                        {
                                                                                                            xtype: 'button',
                                                                                                            id: 'UserResetForm',
                                                                                                            itemId: 'UserResetForm',
                                                                                                            width: 97,
                                                                                                            text: 'Reset Form'
                                                                                                        }
                                                                                                    ]
                                                                                                }
                                                                                            ]
                                                                                        }
                                                                                    ]
                                                                                }
                                                                            ]
                                                                        },
                                                                        {
                                                                            xtype: 'tbspacer',
                                                                            flex: 0,
                                                                            height: 238,
                                                                            width: 22
                                                                        },
                                                                        {
                                                                            xtype: 'container',
                                                                            flex: 0,
                                                                            height: 186,
                                                                            width: 567,
                                                                            layout: 'vbox',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'textfield',
                                                                                    flex: 0,
                                                                                    id: 'username',
                                                                                    itemId: 'username',
                                                                                    width: 301,
                                                                                    fieldLabel: 'User Name'
                                                                                },
                                                                                {
                                                                                    xtype: 'textfield',
                                                                                    flex: 0,
                                                                                    id: 'password',
                                                                                    itemId: 'password',
                                                                                    width: 299,
                                                                                    fieldLabel: 'Password'
                                                                                },
                                                                                {
                                                                                    xtype: 'textfield',
                                                                                    flex: 0,
                                                                                    height: 106,
                                                                                    id: 'address',
                                                                                    itemId: 'address',
                                                                                    width: 300,
                                                                                    fieldLabel: 'Billing Address'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    height: 56,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            flex: 0,
                                                            width: 110,
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'UserSearch',
                                                                    width: 92,
                                                                    text: 'Search'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            flex: 0,
                                                            width: 422,
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'UserSearchBar',
                                                                    itemId: 'UserSearchBar',
                                                                    width: 387,
                                                                    fieldLabel: '',
                                                                    emptyText: 'Search User'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            flex: 0,
                                                            width: 126,
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'UserResetSearch',
                                                                    itemId: 'UserResetSearch',
                                                                    width: 102,
                                                                    text: 'Reset'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            flex: 0,
                                            height: 199,
                                            id: 'userinfogrid',
                                            itemId: 'userinfogrid',
                                            title: 'User Information',
                                            store: 'UserStore',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    id: 'userid',
                                                    itemId: 'userid',
                                                    dataIndex: 'id',
                                                    text: 'ID'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    id: 'userfname',
                                                    itemId: 'userfname',
                                                    width: 125,
                                                    dataIndex: 'fname',
                                                    text: 'First Name'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    id: 'userlname',
                                                    itemId: 'userlname',
                                                    width: 139,
                                                    dataIndex: 'lname',
                                                    text: 'Last Name'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    id: 'useremail',
                                                    itemId: 'useremail',
                                                    width: 131,
                                                    dataIndex: 'email',
                                                    text: 'Email'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    id: 'userusername',
                                                    itemId: 'userusername',
                                                    width: 121,
                                                    dataIndex: 'username',
                                                    text: 'User Name'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    id: 'userpassword',
                                                    itemId: 'userpassword',
                                                    dataIndex: 'password',
                                                    text: 'Password'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    id: 'useraddress',
                                                    itemId: 'useraddress',
                                                    width: 179,
                                                    dataIndex: 'address',
                                                    text: 'Billing Address'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'MenuTab5',
                                    itemId: 'MenuTab5',
                                    title: 'Manage Books',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            height: 381,
                                            id: 'BooksForm',
                                            itemId: 'BooksForm',
                                            bodyPadding: 10,
                                            title: 'Manage Books',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'fieldcontainer',
                                                    flex: 6,
                                                    height: 212,
                                                    width: 262,
                                                    fieldLabel: 'Book Info',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'displayfield',
                                                                    flex: 0,
                                                                    id: 'BookId',
                                                                    itemId: 'BookId',
                                                                    fieldLabel: 'Id'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    flex: 0,
                                                                    id: 'BookTitle',
                                                                    itemId: 'BookTitle',
                                                                    fieldLabel: 'Title'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'BookCover',
                                                                    itemId: 'BookCover',
                                                                    fieldLabel: 'Cover'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    flex: 0,
                                                                    id: 'BookAuthor',
                                                                    itemId: 'BookAuthor',
                                                                    fieldLabel: 'Author'
                                                                },
                                                                {
                                                                    xtype: 'textareafield',
                                                                    id: 'BookDesc',
                                                                    itemId: 'BookDesc',
                                                                    fieldLabel: 'Description'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 0,
                                                            width: 26
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    flex: 0,
                                                                    id: 'BookDate',
                                                                    itemId: 'BookDate',
                                                                    fieldLabel: 'Publish Date'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    flex: 0,
                                                                    id: 'BookBest',
                                                                    itemId: 'BookBest',
                                                                    fieldLabel: 'Best Seller',
                                                                    boxLabel: ''
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'BookPerc',
                                                                    itemId: 'BookPerc',
                                                                    fieldLabel: '% Off'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'BookOPrice',
                                                                    itemId: 'BookOPrice',
                                                                    fieldLabel: 'Original Price'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'BookSPrice',
                                                                    itemId: 'BookSPrice',
                                                                    fieldLabel: 'Sale Price'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'BookAvail',
                                                                    itemId: 'BookAvail',
                                                                    fieldLabel: 'Available'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'BookCheck',
                                                                    itemId: 'BookCheck',
                                                                    fieldLabel: 'Checked-out'
                                                                },
                                                                {
                                                                    xtype: 'displayfield',
                                                                    id: 'BookStatus',
                                                                    itemId: 'BookStatus',
                                                                    fieldLabel: 'Status'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    height: 60,
                                                    layout: 'hbox',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            height: 38,
                                                            id: 'BookReset',
                                                            itemId: 'BookReset',
                                                            width: 100,
                                                            text: 'Reset'
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            height: 38,
                                                            width: 291
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            height: 38,
                                                            id: 'BookCreate',
                                                            itemId: 'BookCreate',
                                                            width: 100,
                                                            text: 'Create'
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            width: 14
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            height: 38,
                                                            id: 'BookUpdate',
                                                            itemId: 'BookUpdate',
                                                            width: 100,
                                                            text: 'Update'
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            width: 14
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            height: 38,
                                                            id: 'BookDelete',
                                                            itemId: 'BookDelete',
                                                            width: 100,
                                                            text: 'Delete'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 0,
                                                    height: 10
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    height: 31,
                                                    layout: 'hbox',
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            id: 'BookSearch',
                                                            itemId: 'BookSearch',
                                                            width: 522,
                                                            fieldLabel: '',
                                                            emptyText: 'Search Title'
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            width: 10
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            height: 27,
                                                            id: 'ResetBtn',
                                                            itemId: 'ResetBtn',
                                                            width: 89,
                                                            text: 'Reset'
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            width: 10
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            height: 27,
                                                            id: 'SearchBtn',
                                                            itemId: 'SearchBtn',
                                                            width: 89,
                                                            text: 'Search'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            height: 508,
                                            id: 'ConfigBooks',
                                            itemId: 'ConfigBooks',
                                            layout: 'fit',
                                            bodyPadding: 10,
                                            title: 'Books Information',
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    height: 290,
                                                    id: 'ConfigBooksGrid',
                                                    itemId: 'ConfigBooksGrid',
                                                    title: '',
                                                    store: 'BookStore',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 242,
                                                            align: 'center',
                                                            dataIndex: 'title',
                                                            text: 'Title'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                                return '<img src="resources/img/' + value + '" align="center"/>';
                                                            },
                                                            width: 189,
                                                            resizable: false,
                                                            align: 'center',
                                                            dataIndex: 'img',
                                                            text: 'Cover'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 209,
                                                            align: 'center',
                                                            dataIndex: 'author',
                                                            text: 'Author'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Desc3',
                                                            itemId: 'Desc',
                                                            width: 171,
                                                            align: 'center',
                                                            dataIndex: 'desc',
                                                            text: 'Book Description'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Date3',
                                                            itemId: 'Date',
                                                            align: 'center',
                                                            dataIndex: 'date',
                                                            text: 'Publish Date'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Perc1',
                                                            itemId: 'Perc',
                                                            align: 'center',
                                                            dataIndex: 'oprice',
                                                            text: '% Off'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Price3',
                                                            itemId: 'Price',
                                                            align: 'center',
                                                            dataIndex: 'oprice',
                                                            text: 'Original Price'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'SalePrice1',
                                                            itemId: 'SalePrice',
                                                            align: 'center',
                                                            dataIndex: 'sprice',
                                                            text: 'Sale Price'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Avail3',
                                                            itemId: 'Avail',
                                                            align: 'center',
                                                            dataIndex: 'avail',
                                                            text: '# of Available Copies'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            id: 'Check',
                                                            itemId: 'Check',
                                                            align: 'center',
                                                            dataIndex: 'avail',
                                                            text: '# of Checked-out Copies'
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        formBind: false,
                                                        enableTextSelection: true
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});