/*
 * File: app/controller/MainCtrl.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W4D3_Homework.controller.MainCtrl', {
    extend: 'Ext.app.Controller',

    id: 'MainCtrl',

    onRegBtnClick: function(button) {
        var form = Ext.getCmp('regForm');
        // Success
        var successCallback = function(resp, ops) {

        	Ext.Msg.show({
        				title : 'Registration Succesful!',
        				msg : 'You have successfully registered',
        				buttons : Ext.Msg.OK,
        				icon : Ext.Msg.INFO
        			});

        };

        // Failure
        var failureCallback = function(resp, ops) {

        	Ext.Msg.show({
        				title : 'Registration Failed!',
        				msg : 'User already exists!',
        				buttons : Ext.Msg.OK,
        				icon : Ext.Msg.WARNING
        			});

        };

        if(form.isValid()){
            Ext.Ajax.request({
        			url : "register",
                    params : {
                        fname: Ext.getCmp('fname').getValue(),
                        lname: Ext.getCmp('lname').getValue(),
                        email: Ext.getCmp('email').getValue(),
                        username: Ext.getCmp('username').getValue(),
                        password: Ext.getCmp('password').getValue()
                    },
        			callback : function(options, success, response){
                        if(response.responseText=='failed'){
                            failureCallback();
                        }else{
                            successCallback();
                        }
                    }
        		});
        }
    },

    init: function(application) {
        this.control({
            "#regBtn": {
                click: this.onRegBtnClick
            }
        });
    }

});
