/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.toolbar.Spacer',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.field.Display',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.Img',
        'Ext.grid.Panel',
        'Ext.grid.column.Column'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 71,
                    itemId: 'headerPanel',
                    header: false,
                    title: 'Header',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 26,
                            id: 'containerHeader',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'tbspacer',
                                    flex: 1,
                                    maxWidth: 150,
                                    minWidth: 150,
                                    width: 150
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    id: 'searchBar',
                                    fieldLabel: 'Search',
                                    displayField: 'ProductName',
                                    queryMode: 'local',
                                    store: 'Products',
                                    valueField: 'ProductName'
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1,
                                    maxWidth: 5,
                                    minWidth: 5,
                                    width: 5
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    id: 'btnSearch',
                                    maxWidth: 110,
                                    minWidth: 110,
                                    width: 110,
                                    text: 'Search Product'
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1,
                                    maxWidth: 80,
                                    minWidth: 80,
                                    width: 80
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    fieldLabel: '   ',
                                    labelSeparator: '                 ',
                                    value: 'Welcome,'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    id: 'welcomeUser'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    hidden: true,
                                    id: 'btnLogout',
                                    text: 'Logout'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'menuPanel',
                    width: 250,
                    layout: 'accordion',
                    collapseDirection: 'left',
                    header: false,
                    title: 'Menu',
                    items: [
                        {
                            xtype: 'panel',
                            id: 'panelWelcome',
                            title: 'Welcome',
                            items: [
                                {
                                    xtype: 'container',
                                    height: 288,
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            id: 'welcomeText',
                                            width: 241,
                                            fieldLabel: '',
                                            labelSeparator: '        ',
                                            value: 'Welcome to Online Shopping! \r\n\r\nOne of the famous online shopping websites along the world.\r\nHigh-quality products available at a much cheaper price.\r\n\r\nShop Now!'
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            height: 150,
                                            maxHeight: 150,
                                            maxWidth: 200,
                                            minHeight: 150,
                                            minWidth: 200,
                                            width: 200
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'panelLogin',
                            title: 'Login',
                            items: [
                                {
                                    xtype: 'form',
                                    height: 200,
                                    id: 'formLogin',
                                    bodyPadding: 10,
                                    header: false,
                                    title: 'My Form',
                                    trackResetOnLoad: true,
                                    items: [
                                        {
                                            xtype: 'tbspacer',
                                            height: 35,
                                            id: 'spacerLogin1',
                                            maxHeight: 35,
                                            maxWidth: 220,
                                            minHeight: 35,
                                            minWidth: 220,
                                            width: 220
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'loginEmail',
                                            fieldLabel: 'Email',
                                            inputType: 'email',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'loginPassword',
                                            fieldLabel: 'Password',
                                            inputType: 'password',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false,
                                            minLength: 8
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            height: 25,
                                            id: 'spaceLogin2',
                                            maxHeight: 25,
                                            maxWidth: 220,
                                            minHeight: 25,
                                            minWidth: 220,
                                            width: 220
                                        },
                                        {
                                            xtype: 'container',
                                            id: 'containerBtn',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle',
                                                pack: 'end'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    formBind: true,
                                                    id: 'btnLogin',
                                                    text: 'Login'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'form',
                                    hidden: true,
                                    id: 'formUser',
                                    bodyPadding: 10,
                                    header: false,
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            id: 'userLogged',
                                            value: 'User has now logged in. \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nYou may now start shopping.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nTo view/update information, you may visit the Account Page.\r\n\r\n\r\n\r\n\r\n\r\n\r\nThank you'
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            height: 100,
                                            maxHeight: 100,
                                            minHeight: 100
                                        },
                                        {
                                            xtype: 'container',
                                            id: 'containerUser',
                                            layout: {
                                                type: 'hbox',
                                                pack: 'end'
                                            },
                                            items: [
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1,
                                                    maxWidth: 130,
                                                    minWidth: 130,
                                                    width: 130
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    height: 35,
                                                    id: 'btnView',
                                                    maxHeight: 35,
                                                    minHeight: 35,
                                                    text: 'View Account'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'panelSignup',
                            title: 'Signup',
                            items: [
                                {
                                    xtype: 'form',
                                    height: 279,
                                    id: 'formSignup',
                                    bodyPadding: 10,
                                    header: false,
                                    title: 'My Form',
                                    trackResetOnLoad: true,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'signupFname',
                                            fieldLabel: 'First Name',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'signupLname',
                                            fieldLabel: 'Last Name',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'datefield',
                                            id: 'signupBdate',
                                            width: 221,
                                            fieldLabel: 'Birthdate',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'signupEmail',
                                            fieldLabel: 'Email',
                                            inputType: 'email',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'signupPassword',
                                            fieldLabel: 'Password',
                                            inputType: 'password',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false,
                                            minLength: 8
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'signupAddress',
                                            fieldLabel: 'Address',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'signupCity',
                                            fieldLabel: 'City',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            id: 'signupCountry',
                                            fieldLabel: 'Country',
                                            allowBlank: false,
                                            allowOnlyWhitespace: false,
                                            displayField: 'CountryName',
                                            queryMode: 'local',
                                            store: 'Country',
                                            valueField: 'CountryName'
                                        },
                                        {
                                            xtype: 'container',
                                            id: 'containerBtn1',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle',
                                                pack: 'end'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    formBind: true,
                                                    id: 'btnSignup',
                                                    text: 'Signup'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    itemId: 'contentPanel',
                    layout: 'fit',
                    title: 'Content',
                    items: [
                        {
                            xtype: 'container',
                            id: 'containerPanel1',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'image',
                                    flex: 3,
                                    height: 98,
                                    width: 498,
                                    src: 'resources/images/image4.png'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            hidden: true,
                            id: 'containerPanel2',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'productsList',
                                    header: false,
                                    title: 'My Grid Panel',
                                    store: 'Products',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            id: 'productName',
                                            dataIndex: 'ProductName',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ProductDescription',
                                            text: 'Description',
                                            flex: 3
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            id: 'productPrice',
                                            dataIndex: 'ProductPrice',
                                            text: 'Price'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 40,
                                    maxHeight: 40,
                                    maxWidth: 150,
                                    minHeight: 40,
                                    minWidth: 150,
                                    width: 150
                                },
                                {
                                    xtype: 'container',
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            id: 'formProduct',
                                            bodyPadding: 10,
                                            header: false,
                                            title: 'My Form',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch',
                                                pack: 'end'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    id: 'textProduct',
                                                    fieldLabel: 'Product Name:',
                                                    allowBlank: false,
                                                    allowOnlyWhitespace: false
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1,
                                                    height: 20,
                                                    maxHeight: 20,
                                                    maxWidth: 15,
                                                    minHeight: 20,
                                                    minWidth: 15,
                                                    width: 15
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'textDescription',
                                                    fieldLabel: 'Description',
                                                    allowBlank: false,
                                                    allowOnlyWhitespace: false
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 1,
                                                    formBind: true,
                                                    height: 35,
                                                    id: 'btnPurchase',
                                                    maxHeight: 35,
                                                    maxWidth: 80,
                                                    minHeight: 35,
                                                    minWidth: 80,
                                                    width: 80,
                                                    text: 'Purchase'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            hidden: true,
                            id: 'containerPanel3',
                            items: [
                                {
                                    xtype: 'form',
                                    id: 'formUpdate',
                                    bodyPadding: 10,
                                    header: false,
                                    title: 'My Form',
                                    items: [
                                        {
                                            xtype: 'container',
                                            id: 'containerInformation',
                                            layout: {
                                                type: 'vbox',
                                                align: 'center',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    disabled: true,
                                                    id: 'cFname',
                                                    fieldLabel: 'First Name',
                                                    allowBlank: false
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    disabled: true,
                                                    id: 'cLname',
                                                    fieldLabel: 'Last Name',
                                                    allowBlank: false
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    disabled: true,
                                                    id: 'cBdate',
                                                    fieldLabel: 'Birthdate'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    disabled: true,
                                                    id: 'cEmail',
                                                    width: 270,
                                                    fieldLabel: 'Email',
                                                    inputType: 'email'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    disabled: true,
                                                    id: 'cPassword',
                                                    fieldLabel: 'Password',
                                                    inputType: 'password'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    disabled: true,
                                                    id: 'cAddress',
                                                    fieldLabel: 'Address'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    disabled: true,
                                                    id: 'cCity',
                                                    fieldLabel: 'City'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    disabled: true,
                                                    hidden: true,
                                                    id: 'cCountry',
                                                    fieldLabel: 'Country'
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            id: 'btnUpdate',
                                                            text: 'Update'
                                                        },
                                                        {
                                                            xtype: 'tbspacer'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            hidden: true,
                                                            id: 'btnSave',
                                                            text: 'Save'
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1,
                                                            maxWidth: 80,
                                                            minWidth: 80,
                                                            width: 80
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});