/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W5D5_Project.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'W5D5_Project.view.MyViewportViewModel',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    viewModel: {
        type: 'myviewport'
    },

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: 'My Form',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'OnlineUsersGrid',
                    itemId: 'OnlineUsersGrid',
                    title: 'My Grid Panel',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'USER'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'date',
                            text: 'LOGIN DATE'
                        }
                    ]
                }
            ]
        }
    ]

});