/*
 * File: app/controller/controllerMain.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.controllerMain', {
    extend: 'Ext.app.Controller',

    id: 'controllerMain',

    onBtnLoginClick: function(button, e, eOpts) {
        if (button) {
            var form1 = Ext.getCmp('formLogin');
            var store = Ext.getStore('Users');
            var username = Ext.getCmp('loginEmail').value;
            var password = Ext.getCmp('loginPassword').value;
            var listUsers = store.data.items;
            var scope = this;

            var storeActive = Ext.getStore('Active');
            var objUser = [{username:username}];

            storeActive.add(objUser);
            Ext.each(listUsers, function(x){
                if (x.data.Email === username && x.data.Password === password){
                    Ext.MessageBox.show({
                    title: 'Login',
                    msg: 'Welcome ' + x.data.FirstName + '!',
                    buttons: Ext.MessageBox.OK,
                    fn: function(btn){
                        if(btn=='OK'){
                            scope.hide();
                        }
                    }
                });

                    }
            });

            form1.form.reset(true);
        }
    },

    onBtnSignupClick: function(button, e, eOpts) {
        if (button){
            var form1 = Ext.getCmp('formSignup');
            var store = Ext.getStore('Users');
            var fname = Ext.getCmp('signupFname').value;
            var lname = Ext.getCmp('signupLname').value;
            var birthdate = Ext.getCmp('signupBdate').value;
            var address = Ext.getCmp('signupAddress').value;
            var city = Ext.getCmp('signupCity').value;
            var country = Ext.getCmp('signupCountry').value;
            var email = Ext.getCmp('signupEmail').value;
            var password = Ext.getCmp('signupPassword').value;

            var objectUser = [{FirstName: fname, LastName: lname, Birthdate: birthdate, Address: address, City: city, Country:country, Email: email, Password: password}];

            store.add(objectUser);

            var userName = Ext.getCmp('signupFname').value;
             Ext.MessageBox.show({
                   msg: 'Saving your data, please wait...',
                   progressText: 'Saving...',
                   width:300,
                   wait:true,
                   waitConfig: {interval:200},
                   icon:'ext-mb-download', //custom class in msg-box.html
                   iconHeight: 50,
                   animateTarget: 'register'
               });
                    setTimeout(function(){
                    //This simulates a long-running operation like a database save or XHR call.
                    //In real code, this would be in a callback function.
                    Ext.MessageBox.hide();
                    Ext.MessageBox.show({
                    title: 'User Registration',
                    msg: 'User "' + userName + '" successfully registered!',
                    buttons: Ext.MessageBox.OK
                });
                }, 5000);

           form1.form.reset(true);

        }
    },

    onBtnSearchClick: function(button, e, eOpts) {
        var store1 = Ext.getStore('Products');
        var product = Ext.getCmp('searchBar').value;
        var listProducts = store1.data.items;

          Ext.each(listProducts, function(x){
                if (x.data.ProductName === product){
                    Ext.MessageBox.show({
                    title: 'Login',
                    msg: 'Welcome ' + x.data.FirstName + '!',
                    buttons: Ext.MessageBox.OK,
                    fn: function(btn){
                        if(btn=='OK'){
                            scope.hide();
                        }
                    }
                });

                    }
            });
    },

    init: function(application) {
        this.control({
            "#btnLogin": {
                click: this.onBtnLoginClick
            },
            "#btnSignup": {
                click: this.onBtnSignupClick
            },
            "#btnSearch": {
                click: this.onBtnSearchClick
            }
        });
    }

});
