/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Demo.controller.MainController', {
    extend: 'Ext.app.Controller',

    id: 'MainController',

    onCreateClick: function() {
        var user, pass, userObj, store;

        user = Ext.getCmp('UserName').getValue();
        pass = Ext.getCmp('PassWord').getValue();
        userObj = {
            userName: user,
            passWord: pass
        };


        store = Ext.getStore('UserStore');
        store.add(userObj);
    },

    onReadClick: function() {
        var user, store;

                user = Ext.getCmp('UserName').getValue();
        store = Ext.getStore('UserStore');

        if(Ext.isEmpty(user)){
            store.clearFilter();
        }else{
        store.filter('userName', user);
        }
    },

    onUpdateClick: function() {
        var user, pass, store;

                        user = Ext.getCmp('UserName').getValue();
        pass = Ext.getCmp('PassWord').getValue();
                store = Ext.getStore('UserStore');

                Ext.each(store.data.items, function(rec){
                   if(rec.data.userName == user){
                       rec.data.passWord = pass;
                   }
                });

        Ext.getCmp('GridPanel').getView().refresh();
    },

    onGridPanelSelectionChange: function(model, selected, eOpts) {
        var select, user, pass;

        select = selected;
        Ext.getCmp('UserName').setValue(select[0].data.userName);
        Ext.getCmp('PassWord').setValue(select[0].data.passWord);
    },

    onDeleteClick: function() {
        var user, store;

                                user = Ext.getCmp('UserName').getValue();
                        store = Ext.getStore('UserStore');

                        Ext.each(store.data.items, function(rec){
                           if(rec.data.userName == user){
                               store.remove(rec);
                           }
                        });

    },

    init: function(application) {
        this.control({
            "#Create": {
                click: this.onCreateClick
            },
            "#Read": {
                click: this.onReadClick
            },
            "#Update": {
                click: this.onUpdateClick
            },
            "#GridPanel": {
                selectionchange: this.onGridPanelSelectionChange
            },
            "#Delete": {
                click: this.onDeleteClick
            }
        });
    }

});
