CREATE TABLE PRODUCTS 
(
  ITEM_ID VARCHAR2(100 BYTE) NOT NULL 
, ITEM_NAME VARCHAR2(100 BYTE) 
, ITEM_CATEGORY VARCHAR2(100 BYTE) 
, ITEM_STOCK NUMBER 
, ITEM_PRICE NUMBER 
, CONSTRAINT PRODUCTS_PK PRIMARY KEY 
  (
    ITEM_ID 
  ));